"""
Forest 500 Data Service for Deforestation Risk Scorer.

Loads pre-processed Forest 500 data from a compact JSON file (generated by
scripts/preprocess_data.py), provides fuzzy company matching, and returns
policy scores, commodity exposure, and assessment details.

Falls back to loading raw CSVs if the preprocessed file is not found.

Forest 500: https://forest500.org/
"""

import os
import json
from difflib import get_close_matches
from typing import Optional

import pandas as pd


class Forest500Service:
    """Service for querying Forest 500 company rankings."""

    def __init__(self, data_dir: str = "data/forest500", preprocessed_path: str = "data/forest500_preprocessed.json"):
        self.data_dir = data_dir
        self.preprocessed_path = preprocessed_path
        self._company_names: list[str] = []
        self._companies: dict = {}  # lowercase name -> pre-computed data
        self._loaded = False
        # Legacy: raw DataFrame for CSV fallback
        self._df: Optional[pd.DataFrame] = None

    def load(self) -> bool:
        """
        Load Forest 500 data. Tries preprocessed JSON first, falls back to raw CSVs.

        Returns True if data was loaded successfully, False otherwise.
        """
        if self._loaded:
            return True

        # Try preprocessed JSON first
        json_path = os.path.abspath(self.preprocessed_path)
        if os.path.exists(json_path):
            return self._load_preprocessed(json_path)

        # Fall back to raw CSVs
        return self._load_raw_csvs()

    def _load_preprocessed(self, json_path: str) -> bool:
        """Load from preprocessed JSON file."""
        try:
            with open(json_path, "r", encoding="utf-8") as f:
                data = json.load(f)

            self._company_names = data.get("company_names", [])
            self._companies = data.get("companies", {})
            self._loaded = True

            print(f"[Forest500] Loaded preprocessed data: {len(self._company_names)} companies")
            return True
        except Exception as e:
            print(f"[Forest500] Failed to load preprocessed data: {e}")
            return False

    def _load_raw_csvs(self) -> bool:
        """Legacy: Load from raw CSV files."""
        csv_path = os.path.abspath(self.data_dir)
        if not os.path.exists(csv_path):
            print(f"[Forest500] Data directory not found: {csv_path}")
            return False

        csv_files = [
            f for f in os.listdir(csv_path)
            if f.endswith(".csv")
        ]

        if not csv_files:
            print(f"[Forest500] No CSV files found in: {csv_path}")
            return False

        frames = []
        for csv_file in csv_files:
            try:
                filepath = os.path.join(csv_path, csv_file)
                df = pd.read_csv(filepath, low_memory=False, encoding="utf-8")
                df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
                frames.append(df)
                print(f"[Forest500] Loaded: {csv_file} ({len(df)} rows)")
            except Exception as e:
                print(f"[Forest500] Failed to load {csv_file}: {e}")

        if not frames:
            print("[Forest500] No valid CSV data loaded.")
            return False

        self._df = pd.concat(frames, ignore_index=True, sort=False)
        print(f"[Forest500] Total rows: {len(self._df)}")

        self._company_names = self._extract_company_names()
        print(f"[Forest500] Unique companies indexed: {len(self._company_names)}")

        self._loaded = True
        return True

    def _extract_company_names(self) -> list[str]:
        """Extract unique company names from DataFrame."""
        if self._df is None:
            return []

        name_columns = [
            "name", "company", "company_name", "organisation",
            "organization", "entity_name", "institution",
        ]

        names = set()
        for col in name_columns:
            if col in self._df.columns:
                col_names = self._df[col].dropna().unique()
                names.update(str(n).strip() for n in col_names if str(n).strip())

        return sorted(names)

    def search(self, company: str, cutoff: float = 0.6) -> dict:
        """
        Search for a company in Forest 500 data using fuzzy matching.

        Args:
            company: Company name to search for
            cutoff: Fuzzy match threshold (0-1)

        Returns:
            Dict with matched company name, policy scores, commodities, and assessment.
        """
        if not self._loaded:
            if not self.load():
                return {
                    "status": "not_available",
                    "error": "Forest 500 data not loaded. See data/README.md for download instructions.",
                }

        # If we have preprocessed data, use the fast path
        if self._companies:
            return self._search_preprocessed(company, cutoff)

        # Legacy: search raw DataFrame
        return self._search_raw(company, cutoff)

    def _search_preprocessed(self, company: str, cutoff: float) -> dict:
        """Search using preprocessed JSON data (fast path)."""
        matches = get_close_matches(
            company.lower(),
            [n.lower() for n in self._company_names],
            n=3,
            cutoff=cutoff,
        )

        if not matches:
            return {
                "status": "not_found",
                "company_searched": company,
                "policy_score": None,
                "commodities": [],
            }

        # Aggregate results from matched companies
        matched_names = []
        best_policy_score = None
        all_commodities = set()
        all_category_scores = {}
        all_metadata = {}
        total_records = 0

        for match_key in matches:
            company_data = self._companies.get(match_key)
            if not company_data:
                continue

            matched_names.extend(company_data.get("names", []))
            total_records += company_data.get("total_records", 0)
            all_commodities.update(company_data.get("commodities", []))

            # Take the first non-null policy score
            ps = company_data.get("policy_score")
            if ps is not None and best_policy_score is None:
                best_policy_score = ps

            # Merge category scores (first match wins)
            for k, v in company_data.get("category_scores", {}).items():
                if k not in all_category_scores:
                    all_category_scores[k] = v

            # Merge metadata (first match wins)
            for k, v in company_data.get("metadata", {}).items():
                if k not in all_metadata:
                    all_metadata[k] = v

        if not matched_names:
            return {
                "status": "not_found",
                "company_searched": company,
                "policy_score": None,
                "commodities": [],
            }

        matched_names = sorted(set(matched_names))

        return {
            "status": "found",
            "company_searched": company,
            "matched_names": matched_names,
            "total_records": total_records,
            "policy_score": best_policy_score,
            "commodities": sorted(all_commodities),
            "category_scores": all_category_scores,
            "metadata": all_metadata,
        }

    def _search_raw(self, company: str, cutoff: float) -> dict:
        """Legacy: search using raw DataFrame."""
        matches = get_close_matches(
            company.lower(),
            [n.lower() for n in self._company_names],
            n=3,
            cutoff=cutoff,
        )

        if not matches:
            return {
                "status": "not_found",
                "company_searched": company,
                "policy_score": None,
                "commodities": [],
            }

        matched_names = []
        for m in matches:
            for orig in self._company_names:
                if orig.lower() == m:
                    matched_names.append(orig)
                    break

        name_columns = [
            "name", "company", "company_name", "organisation",
            "organization", "entity_name", "institution",
        ]

        mask = pd.Series(False, index=self._df.index)
        for col in name_columns:
            if col in self._df.columns:
                mask |= self._df[col].astype(str).str.strip().isin(matched_names)

        filtered = self._df[mask]

        if filtered.empty:
            return {
                "status": "not_found",
                "company_searched": company,
                "policy_score": None,
                "commodities": [],
            }

        policy_score = self._extract_score(filtered)
        commodities = self._extract_commodities(filtered)
        category_scores = self._extract_category_scores(filtered)
        metadata = self._extract_metadata(filtered)

        return {
            "status": "found",
            "company_searched": company,
            "matched_names": matched_names,
            "total_records": len(filtered),
            "policy_score": policy_score,
            "commodities": commodities,
            "category_scores": category_scores,
            "metadata": metadata,
        }

    def _extract_score(self, df: pd.DataFrame) -> Optional[float]:
        """Extract the overall/policy score."""
        score_columns = [
            "total_score", "overall_score", "score", "total",
            "policy_score", "total_percentage", "percentage",
        ]
        for col in score_columns:
            if col in df.columns:
                numeric = pd.to_numeric(df[col], errors="coerce")
                valid = numeric.dropna()
                if not valid.empty:
                    return round(float(valid.iloc[0]), 1)
        return None

    def _extract_commodities(self, df: pd.DataFrame) -> list[str]:
        """Extract commodity data from Forest 500."""
        commodity_cols = [
            col for col in df.columns
            if any(kw in col.lower() for kw in [
                "commodity", "palm", "soy", "beef", "cattle",
                "timber", "pulp", "paper", "cocoa", "rubber",
                "coffee",
            ])
        ]

        commodities = set()
        for col in commodity_cols:
            numeric = pd.to_numeric(df[col], errors="coerce")
            if numeric.sum() > 0:
                for keyword in [
                    "palm oil", "soy", "beef", "cattle", "timber",
                    "pulp", "paper", "cocoa", "rubber", "coffee",
                ]:
                    if keyword in col:
                        commodities.add(keyword.title())
                        break

        text_cols = ["commodity", "commodities", "key_commodities"]
        for col in text_cols:
            if col in df.columns:
                vals = df[col].dropna().unique()
                for v in vals:
                    for item in str(v).split(","):
                        clean = item.strip()
                        if clean:
                            commodities.add(clean.title())

        return sorted(commodities)

    def _extract_category_scores(self, df: pd.DataFrame) -> dict:
        """Extract individual category scores from Forest 500."""
        category_keywords = [
            "governance", "commitment", "transparency", "implementation",
            "social", "reporting", "traceability", "monitoring",
        ]

        scores = {}
        for col in df.columns:
            for keyword in category_keywords:
                if keyword in col.lower():
                    numeric = pd.to_numeric(df[col], errors="coerce")
                    valid = numeric.dropna()
                    if not valid.empty:
                        scores[keyword] = round(float(valid.iloc[0]), 1)
                    break

        return scores

    def _extract_metadata(self, df: pd.DataFrame) -> dict:
        """Extract company metadata like headquarters, sector, etc."""
        metadata_cols = {
            "headquarters": ["headquarters", "hq", "country", "hq_country"],
            "sector": ["sector", "industry", "category", "type"],
            "jurisdiction": ["jurisdiction", "jurisdiction_country"],
        }

        result = {}
        for key, possible_cols in metadata_cols.items():
            for col in possible_cols:
                if col in df.columns:
                    val = df[col].dropna()
                    if not val.empty:
                        result[key] = str(val.iloc[0]).strip()
                        break

        return result

    @property
    def is_loaded(self) -> bool:
        return self._loaded

    @property
    def company_count(self) -> int:
        return len(self._company_names)
