"""
Trase Data Service for Deforestation Risk Scorer.

Loads pre-processed Trase data from a compact JSON file (generated by
scripts/preprocess_data.py), provides fuzzy company name matching, and
returns commodity flows, sourcing regions, and deforestation risk indicators.

Falls back to loading raw CSVs if the preprocessed file is not found.

Trase data: https://supplychains.trase.earth/
"""

import os
import json
from difflib import get_close_matches
from typing import Optional

import pandas as pd


class TraseService:
    """Service for querying Trase supply chain data."""

    def __init__(self, data_dir: str = "data/trase", preprocessed_path: str = "data/trase_preprocessed.json"):
        self.data_dir = data_dir
        self.preprocessed_path = preprocessed_path
        self._company_names: list[str] = []
        self._companies: dict = {}  # lowercase name -> pre-computed data
        self._loaded = False
        # Legacy: raw DataFrame for CSV fallback
        self._df: Optional[pd.DataFrame] = None

    def load(self) -> bool:
        """
        Load Trase data. Tries preprocessed JSON first, falls back to raw CSVs.

        Returns True if data was loaded successfully, False otherwise.
        """
        if self._loaded:
            return True

        # Try preprocessed JSON first
        json_path = os.path.abspath(self.preprocessed_path)
        if os.path.exists(json_path):
            return self._load_preprocessed(json_path)

        # Fall back to raw CSVs
        return self._load_raw_csvs()

    def _load_preprocessed(self, json_path: str) -> bool:
        """Load from preprocessed JSON file."""
        try:
            with open(json_path, "r", encoding="utf-8") as f:
                data = json.load(f)

            self._company_names = data.get("company_names", [])
            self._companies = data.get("companies", {})
            self._loaded = True

            print(f"[Trase] Loaded preprocessed data: {len(self._company_names)} companies")
            return True
        except Exception as e:
            print(f"[Trase] Failed to load preprocessed data: {e}")
            return False

    def _load_raw_csvs(self) -> bool:
        """Legacy: Load from raw CSV files."""
        import glob

        csv_path = os.path.abspath(self.data_dir)
        if not os.path.exists(csv_path):
            print(f"[Trase] Data directory not found: {csv_path}")
            return False

        csv_files = glob.glob(os.path.join(csv_path, "*.csv"))
        if not csv_files:
            print(f"[Trase] No CSV files found in: {csv_path}")
            return False

        frames = []
        for csv_file in csv_files:
            try:
                df = pd.read_csv(csv_file, low_memory=False, encoding="utf-8")
                df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
                frames.append(df)
                print(f"[Trase] Loaded: {os.path.basename(csv_file)} ({len(df)} rows)")
            except Exception as e:
                print(f"[Trase] Failed to load {os.path.basename(csv_file)}: {e}")

        if not frames:
            print("[Trase] No valid CSV data loaded.")
            return False

        self._df = pd.concat(frames, ignore_index=True, sort=False)
        print(f"[Trase] Total unified rows: {len(self._df)}")

        self._company_names = self._extract_company_names()
        print(f"[Trase] Unique company names indexed: {len(self._company_names)}")

        self._loaded = True
        return True

    def _extract_company_names(self) -> list[str]:
        """Extract unique company/exporter/importer names from DataFrame."""
        if self._df is None:
            return []

        name_columns = [
            "exporter", "importer", "company", "trader",
            "exporter_name", "importer_name", "company_name",
            "exporter_group", "importer_group",
        ]

        names = set()
        for col in name_columns:
            if col in self._df.columns:
                col_names = self._df[col].dropna().unique()
                names.update(str(n).strip() for n in col_names if str(n).strip())

        return sorted(names)

    def search(self, company: str, cutoff: float = 0.6) -> dict:
        """
        Search for a company in Trase data using fuzzy matching.

        Args:
            company: Company name to search for
            cutoff: Fuzzy match threshold (0-1)

        Returns:
            Dict with matched company info, commodities, regions, and volumes.
        """
        if not self._loaded:
            if not self.load():
                return {
                    "status": "not_available",
                    "error": "Trase data not loaded. See data/README.md for download instructions.",
                }

        # If we have preprocessed data, use the fast path
        if self._companies:
            return self._search_preprocessed(company, cutoff)

        # Legacy: search raw DataFrame
        return self._search_raw(company, cutoff)

    def _search_preprocessed(self, company: str, cutoff: float) -> dict:
        """Search using preprocessed JSON data (fast path)."""
        # Fuzzy match company name
        matches = get_close_matches(
            company.lower(),
            [n.lower() for n in self._company_names],
            n=5,
            cutoff=cutoff,
        )

        if not matches:
            return {
                "status": "not_found",
                "company_searched": company,
                "commodities": [],
                "regions": [],
            }

        # Aggregate results from all matched companies
        all_commodities = set()
        all_regions = set()
        all_volumes = {}
        all_deforestation = {}
        matched_names = []
        total_records = 0

        for match_key in matches:
            company_data = self._companies.get(match_key)
            if not company_data:
                continue

            matched_names.extend(company_data.get("names", []))
            total_records += company_data.get("total_records", 0)
            all_commodities.update(company_data.get("commodities", []))
            all_regions.update(company_data.get("regions", []))

            for vc, vdata in company_data.get("volumes", {}).items():
                if vc in all_volumes:
                    all_volumes[vc]["total"] = round(all_volumes[vc]["total"] + vdata["total"], 2)
                    all_volumes[vc]["records"] += vdata["records"]
                else:
                    all_volumes[vc] = dict(vdata)

            for dc, ddata in company_data.get("deforestation_indicators", {}).items():
                if dc in all_deforestation:
                    all_deforestation[dc]["total"] = round(all_deforestation[dc]["total"] + ddata["total"], 2)
                    all_deforestation[dc]["max"] = max(all_deforestation[dc]["max"], ddata["max"])
                    all_deforestation[dc]["records"] += ddata["records"]
                else:
                    all_deforestation[dc] = dict(ddata)

        if not matched_names:
            return {
                "status": "not_found",
                "company_searched": company,
                "commodities": [],
                "regions": [],
            }

        # Deduplicate names
        matched_names = sorted(set(matched_names))

        return {
            "status": "found",
            "company_searched": company,
            "matched_names": matched_names,
            "total_records": total_records,
            "commodities": sorted(all_commodities),
            "regions": sorted(all_regions),
            "volumes": all_volumes,
            "deforestation_indicators": all_deforestation,
        }

    def _search_raw(self, company: str, cutoff: float) -> dict:
        """Legacy: search using raw DataFrame."""
        matches = get_close_matches(
            company.lower(),
            [n.lower() for n in self._company_names],
            n=5,
            cutoff=cutoff,
        )

        if not matches:
            return {
                "status": "not_found",
                "company_searched": company,
                "commodities": [],
                "regions": [],
            }

        matched_names = []
        for m in matches:
            for orig in self._company_names:
                if orig.lower() == m:
                    matched_names.append(orig)
                    break

        name_columns = [
            "exporter", "importer", "company", "trader",
            "exporter_name", "importer_name", "company_name",
            "exporter_group", "importer_group",
        ]

        mask = pd.Series(False, index=self._df.index)
        for col in name_columns:
            if col in self._df.columns:
                mask |= self._df[col].astype(str).str.strip().isin(matched_names)

        filtered = self._df[mask]

        if filtered.empty:
            return {
                "status": "not_found",
                "company_searched": company,
                "commodities": [],
                "regions": [],
            }

        commodities = self._extract_field(filtered, [
            "commodity", "product", "commodity_name", "product_type",
        ])
        regions = self._extract_field(filtered, [
            "country_of_production", "country", "source_country",
        ])
        volume_info = self._extract_volumes(filtered)
        deforestation_data = self._extract_deforestation_indicators(filtered)

        return {
            "status": "found",
            "company_searched": company,
            "matched_names": matched_names,
            "total_records": len(filtered),
            "commodities": commodities,
            "regions": regions,
            "volumes": volume_info,
            "deforestation_indicators": deforestation_data,
        }

    def _extract_field(self, df: pd.DataFrame, columns: list[str]) -> list[str]:
        """Extract unique non-null values from multiple possible columns."""
        values = set()
        for col in columns:
            if col in df.columns:
                col_vals = df[col].dropna().unique()
                values.update(str(v).strip() for v in col_vals if str(v).strip())
        return sorted(values)

    def _extract_volumes(self, df: pd.DataFrame) -> dict:
        """Extract volume/trade data if columns exist."""
        volume_cols = [
            "volume", "fob", "trade_value", "quantity",
            "soy_equivalent_tonnes", "tonnes",
        ]
        result = {}
        for col in volume_cols:
            if col in df.columns:
                numeric = pd.to_numeric(df[col], errors="coerce")
                result[col] = {
                    "total": round(float(numeric.sum()), 2),
                    "mean": round(float(numeric.mean()), 2),
                    "records": int(numeric.count()),
                }
        return result

    def _extract_deforestation_indicators(self, df: pd.DataFrame) -> dict:
        """Extract deforestation-related columns if they exist."""
        deforestation_cols = [
            col for col in df.columns
            if any(kw in col.lower() for kw in [
                "deforestation", "forest", "land_use", "soy_deforestation",
                "territory_deforestation", "biome_deforestation",
            ])
        ]
        result = {}
        for col in deforestation_cols:
            numeric = pd.to_numeric(df[col], errors="coerce")
            if numeric.count() > 0:
                result[col] = {
                    "total": round(float(numeric.sum()), 2),
                    "mean": round(float(numeric.mean()), 2),
                    "max": round(float(numeric.max()), 2),
                    "records": int(numeric.count()),
                }
        return result

    @property
    def is_loaded(self) -> bool:
        return self._loaded

    @property
    def company_count(self) -> int:
        return len(self._company_names)

    @property
    def record_count(self) -> int:
        if self._companies:
            return sum(c.get("total_records", 0) for c in self._companies.values())
        return len(self._df) if self._df is not None else 0
